spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100

---
spring.config.activate.on-profile: local

spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_log: true
        format_sql: true
    show-sql: true

storage:
  datasource:
    core:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/lezhin
      username: root
      password: mysql
      pool-name: main-db-pool
      data-source-properties:
        rewriteBatchedStatements: true

logging:
  level:
    org:
      springframework:
        jdbc: debug
